/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8eb89e49-d1ab-4dd3-a580-9a0eba0bd4bd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_y7tQymKki",
    "aws_user_pools_web_client_id": "25irfkau0of791vv6i3gccfgq4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://fectjjmpwfa7jn2eqhh32gexrq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "quasardemo-20200912200929-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d3alanaoyifrhy.cloudfront.net"
};


export default awsmobile;
